### ISSUE TITLE
US1

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#1]
## Value Proposition

**As a** user  
**I want to** view a list of parts  
**so that** i have an overview on parts
​

## Description

![Image](https://github.com/matschi3/testarea/assets/114819127/df9f78ea-89a2-4bc5-9d6d-4193d2480b69)

 

## Acceptance Criteria

- [ ] user can see a list of all parts with basic partData
- [ ] listItems have same size
- [ ] listItems width almost screenWidth
- [ ] list scrolls vertically
- [ ] heading is always visible
      ​

## Tasks

- [ ] create branch 
- [ ] create dummy Partsdata
- [ ] display PartsData on FrontEnd
- [ ] create global styles
- [ ] create basic partCard style
      ​
