### ISSUE TITLE
US8 // items - newItemPage

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#15]
## Value Proposition        
  
**As a** `user`  
**I want to** have a page for new items
**so that** i can view my parts with specific value on this separate page
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250014048-c7f0fdb9-7131-4db5-a00d-98543957e679.png)

 

## Acceptance Criteria

- [ ] user can see a button called `neues ITEM` directing to a new page
on new page:
- [ ] the pages `title` is `neues ITEM`
- [ ] the heading is `neues ITEM`
- [ ] there are partCards listed with `inAssembler: true`
- [ ] on top left corner, user can see a button called `zurück` directing back to parts
- partCards as they are

## Tasks
                  
- [ ] create branch `feature/us7/new-parts-page`
- [ ] create new file `/pages/new-part`
- [ ] insert LinkTo component directing to `/new-part`
- [ ] insert Header component
- [ ] insert LinkBack component routing user back to `parts-page`
- [ ] display all relevant partsData from dummy partsData
      ​

**Comment by actyvystom** [comment]
A nice one! 
I suggest a few changes:
- Less technical title and value proposition, e.g. "New items overview" for the title and 
- as value proposition 
e.g. 
> As a user 
> I want to be have an overview of new items
> so that I can see which ones are currently in assembly

Cheers, Thomas

**Comment by matschi3** [comment]
Thanks for your review! 👌

good advice. i really need to get rid of the technical language at title and value proposition 🧐
