### ISSUE TITLE
US9 // items - newItem

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#16]
## Value Proposition           
  
**As a** `user`  
**I want to** assemble my previous chosen `parts`, listed on `new-item` page
**so that** i can see a bunch of `parts` as an created `item`
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250061465-cdc7e393-21bc-4f85-becf-ea2731c70373.png)

 

## Acceptance Criteria

- [ ] user can see a button called `verarbeiten` or sth. like that directing to a new page
on new page:
- [ ] the pages `title` is `ITEMS`
- [ ] the heading is `ITEMS`
- [ ] there are `partCards` listed inside a new created `itemCard`
- [ ] on the `itemCard` there is displayed a defaultImage and the dateAssembled
- [ ] on top left corner, user can see a button called `zurück` directing back to `parts-page`

## Tasks
                  
- [ ] create branch `feature/us9/assembleNewItem`
- [ ] create new file `/pages/items`
- [ ] insert `LinkTo` component directing to /items
- [ ] insert `Header` component
- [ ] insert `LinkBack` component routing user back to parts-page
- [ ] create little `itemsDummyData`
- [ ] on 'assembleButton` click:
    - [ ] create new item from displayed ones
    - [ ] add chosen `parts` to `item` data (uuid's)
    - [ ] set status `isAssembled` to each of the `parts`
    - [ ] set `dateAssembled` to `parts` and `item` ​

**Comment by Dariastep** [comment]
Well done, Nils! LGTM :tada:
