### ISSUE TITLE
US10 // parts - editPart

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#17]
## Value Proposition           
  
**As a** `user`  
**I want to** edit my created `parts`
**so that** i can change values, if they are entered incorrect on creation
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250066855-34ff6d99-acc6-4e3a-9ac1-b371669f60bd.png)

 

## Acceptance Criteria

- [ ] user can see a button called `bearbeiten` or sth. like that on each partCard
- [ ] user gets directed to an edit page for the specific `part`
- [ ] the pages `title` is `TEIL bearbeiten`
- [ ] the heading is `TEIL bearbeiten`
- [ ] on the `edit-part` page you can enter name, price and purchasingPlace
- [ ] you can also choose the newParts category by dropdown
- [ ] on the bottom of the form there is a submitEdit button, submitting changes and sending user back to parts-page
- [ ] on top left corner, user can see a button called `zurück` directing back to `parts-page`

## Tasks
                  
- [ ] create branch `feature/us10/edit-part`
- [ ] create `bearbeiten` button directing to `/[uuid]/edit-part` on PartCard component
- [ ] create new file `/pages/[uuid]/edit-part`
- [ ] insert `Header` component
- [ ] insert `LinkBack` component routing user back to parts-page
- [ ] insert `PartForm` component with other props (+defaultValues)
on Forms 'submitButton` click:
    - [ ] edit specific item in state
    - [ ] send user back to `parts-page` 
      ​

**Comment by Danielschuetzle** [comment]
LGTM
