### ISSUE TITLE
US2

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#2]
## Value Proposition 

**As a** user  
**I want to** see a colored marker 
**so that** i know in which status a part is in immediately
​

## Description

![Image](https://user-images.githubusercontent.com/114819127/247960328-b525316d-90ce-4689-b398-58fdf52787ea.png)

 

## Acceptance Criteria

- [ ] user can see colored marker on each part
- [ ] marker has different color depending on its status
- [ ] marker has different status-text depending on its status
      ​

## Tasks
                  
- [ ] create branch
- [ ] display basic statusMarker
- [ ] display status-text depending on dummy partsData
- [ ] colorize statusMarker depending on dummy partsData
- [ ] add statusMarker style to partCard style
      ​

**Comment by JonasDaJones** [comment]
Jo
