### ISSUE TITLE
US11 // parts - highlight active filter

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#20]
## Value Proposition           
  
**As a** `user`  
**I want to** see the filter i clicked on highlighted
**so that** i have an better overview on which filters i chose
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250529997-66cf819d-cdd4-4cd3-acca-6fd85eeec496.png)

 

## Acceptance Criteria

- [ ] user can see a highlighting on the chosen category filter 
- [ ] user can see a highlighting on the chosen status filter
- [ ] on change of the filter, the highlighting switches to selected ones

## Tasks
                  
- [ ] create branch `feature/us11/highlight-filter`
- [ ] create states for `activeCategoryFilter` and `activeStatusFilter`
- [ ] add setState to filterButtons onClick on each of the filterButtons
      ​

**Comment by Katemuya** [comment]
LGTM 🚀
