### ISSUE TITLE
US12 // parts - delete a part

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#22]
## Value Proposition           
  
**As a** `user`  
**I want to** delete a part
**so that** i can get rid of it, if anything was wrong with it

    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250574029-238852fa-faa7-4174-82cf-c7d67aa8f8a9.png)

 

## Acceptance Criteria

- [x] user can see a button with text 'löschen' on each parts `detail-page` 

a click on the button: 
- [x] deletes the part
- [x] sends user back to `parts-page`

## Tasks
                  
- [x] create branch `feature/us12/delete-part` and `cd` into it
- [x] add button on `pages/[uuid]/index`
- [x] add onClick function for delete of part with uuid
- [x] add function in UsePartStore to delete part and call it inside delete function
- [x] add routing to send user back to `parts-page`
      ​

**Comment by ThysBat** [comment]
Nice and clear US! LGTM 🚀
