### ISSUE TITLE
US13 // db - database setup

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#23]
## Value Proposition           
  
**As a** `user` 
**I want to** use the app on another device
**so that** i can have the same parts and items an all my devices
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250579970-da0a60be-b222-460d-928c-8632496c2d6b.png)

 

## Acceptance Criteria

- [ ] user can see the app as it was before
- [ ] when `adding a part` or `assembling an item`, changes stay on device/browser switch

## Tasks
                  
- [ ] create branch `feature/us13/establishDatabase`
- [ ] setup atlas mongo db with dummyData
- [ ] setup `.env` to connect with db
- [ ] add schemes for `parts` and `items`
- [ ] add `C.R.U.D.` operations
- [ ] replace 'zustand' states for `parts` and `items` with db
- [ ] check and edit functionalities for db

**Comment by JonasDaJones** [comment]
very cool you have those detailed tasks. Works for me.
