### ISSUE TITLE
US14 // nav - add basic footer + basic navigation

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#24]
## Value Proposition           
  
**As a** `user` 
**I want to** easily navigate
**so that** i can switch to `items-page` without the need to create a new item
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250592750-6241cf1a-4f96-40c5-9dd0-721e31861f11.png)

 

## Acceptance Criteria

- [ ] user can see two buttons at the bottom of the page
- [ ] left button opens up `parts-page`
- [ ] right button opens up `items-page`
- [ ] cards scroll behind the two buttons
- [ ] buttons only on `parts-page`/`index` and `items-page`

## Tasks
                  
- [ ] create branch `feature/us14/basicFooter`
- [ ] setup `StyledFooter` component to fit criteria
- [ ] add `StyledButton` for each 'parts' and 'items'
- [ ] add routing for buttons
      ​

**Comment by MichanNan** [comment]
LGTM 🚀
