### ISSUE TITLE
US15 // categories - new categories page

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#26]
## Value Proposition           
  
**As a** `user` 
**I want to** add my own categories
**so that** i can be more creative using the app
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250864167-d25fef02-2cbd-40c2-adad-61be741b869f.png)

 

## Acceptance Criteria

- [ ] user can see a third button at the bottom right of the page with text `Kategorien`
- [ ] button opens up new `categories-page`
on new page:
- [ ] the `title` and `heading` of the page is `KATEGORIEN` 
- [ ] on the top is a `input field` for adding a new category next to a `submit-button`  
- [ ] below is a `list` of existing categories 

## Tasks
                  
- [ ] create branch `feature/us15/categories-page` and switch into it
- [ ] insert `Header` component
- [ ] insert `Footer` component
- [ ] add new link in Footer for `Kategorien` + routing
- [ ] map() categories + render list of all categories
- [ ] create `inputField` with `submitButton`
- [ ] create function to add new category to categories

      ​

**Comment by ThysBat** [comment]
LGTM 🚀 Easy to read, easy to understand, nice! 👍
