### ISSUE TITLE
US16 // categories - edit-delete-category

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#27]
## Value Proposition           
  
**As a** `user` 
**I want to** edit and delete categories
**so that** i am able to be more flexible in usage
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250894814-3c113135-ae7f-4a4e-8d80-c0741fd790d3.png)

 

## Acceptance Criteria

- [x] next to each `category` listed, there is a button with text `bearbeiten` and another with text `löschen`
- [x] `löschen` button deletes the category next to the button
- [x] `bearbeiten` button opens up an `input-field` to edit category with `ok` button to submit
- [x] click on `bearbeiten` again closes input-field back

## Tasks
                  
- [x] create branch `feature/us16/edit-delete-category` and switch into it
- [x] create container for like a `category-card`
- [x] add buttons for `edit` and `delete`
- [x] setup onClick function to display `input-field` with submit-button and hide on re-click
- [x] setup function to update category on db on `ok`-submit click
- [x] setup function to delete category entry from db on `delete` click

      ​

**Comment by ThysBat** [comment]
LGTM 🚀 I like how you keep your stories short simple!
