### ISSUE TITLE
US17 // parts - image upload

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#28]
## Value Proposition           
  
**As a** `user` 
**I want to** upload my own picture as parts image
**so that** i instantly see differences of my parts
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/250901471-5216c8fa-1f08-4cc3-8afa-435507238183.png)

 

## Acceptance Criteria

- [ ] on `create-part` page there is an `image-upload-field` below the other form-fields
- [ ] next to it is a submit-button
- [ ] `hinzufügen` button creates new part and sends user back to `parts-page` like before

## Tasks
                  
- [ ] create branch `feature/us17/parts-image-upload` and switch into it
- [ ] create `image-upload-field` on `PartForm` 
- [ ] setup `cloudinary`, add cloudinary-url to list, manage connection
- [ ] add returned imgURL into parts data
- [ ] make sure it works on `/[uuid]/edit` as well

      ​

**Comment by M-Bohmann** [comment]
LGTM! 👍
