### ISSUE TITLE
US3

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#3]
## Value Proposition 

**As a** user  
**I want to** have a toggleButton 
**so that** i can easily toggle a status for each part
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/247967419-fe43943b-8418-4db1-be10-8a88ea2562c4.png)

 

## Acceptance Criteria

- [ ] user can see toggleButton on each part
- [ ] toggleButton has different color depending on its status
- [ ] toggleButton has different icon depending on its status
      ​

## Tasks
                  
- [ ] create branch
- [ ] display basic toggleButton
- [ ] display different icon depending on dummy partsData
- [ ] colorize statusMarker depending on dummy partsData
- [ ] toggle the inAssembler value onClick
- [ ] add toggleButton style to partCard style
      ​

**Comment by matschi3** [comment]
good question, thanks :)
for now it will not have a decent function. it was just part of the big plan.
makes sense to skip this to a later userStory so it has a real advantage when assembling parts to an item.
i have much more simple tasks to put in user-stories before.
so i will keep it as 'us3' on my backlog for maybe next sprint

**Comment by matschi3** [comment]
// reworked

**Comment by actyvystom** [comment]
Basically a nice one!
I probably don't get the idea of your project correctly (my bad 🙈 ), so just a few comments on general issues with this US:
- Try to avoid technical language in the title (e.g. _Toggle parts for later assembly_)
- You don't need to refer to other user stories in your value proposition ([US8])
- Your **acceptance criteria** should contain more detail, e.g. _using the toggle button sets the displayed status to either ... or ..._ 
Cheers, Thomas

**Comment by matschi3** [comment]
Thanks for your time @actyvystom !
i reworked your mentioned tasks.

Basic idea is to 
keep track of what parts i bought,
what their price was,
keep track of items i created from parts
and so on :)

**Comment by JonasDaJones** [comment]
Thank you, i think this works.

**Comment by matschi3** [comment]
Thanks for your time @JonasDaJones  👌
