### ISSUE TITLE
US18 // items - add target price

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#34]
## Value Proposition           
  
**As a** `user` 
**I want to** set a targetPrice for selling
**so that** i have it ready when i'm selling it
    
## Description
 

![Image](https://user-images.githubusercontent.com/114819127/252337875-71b3557d-56e0-4d61-8a67-efac0b8ba2c5.png)

 
  
## Acceptance Criteria

- [ ] on `items-page` on each `item-card` there is a button called `VK einstellen` 
- [ ] button opens a popUp with `input` to enter a number
- [ ] on popUp there are two buttons: `abbrechen` + `bestätigen`
- [ ] `abbrechen` closes the popUp with data unchanged
- [ ] `bestätigen` will add the entered number to items data
- [ ] entered number gets displayed on `item-card`
- [ ] also `Gewinn` gets calculated and displayed on `item-card`

## Tasks
                  
- [ ] create branch `feature/us18/item-addTargetPrice` and switch into it
- [ ] create a popUp component with buttons (maybe reusable for later stuff if it makes sense)
- [ ] create `button` on `itemCard` to open up the popUp
- [ ] add function to edit targetPrice value for this specific item
- [ ] render `VK:` + calculated `Gewinn` on `item-card`

**Comment by vaupunkt** [comment]
lgtm 💪
