### ISSUE TITLE
US19 // items - add soldForPrice when sold

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#35]
## Value Proposition           
   
**As a** `user` 
**I want to** set a price i sold the item for
**so that** i can keep track of sales
    
## Description
 

![Image](https://user-images.githubusercontent.com/114819127/252344199-b685576d-e714-42ce-b148-f9ce94478615.png)

 
  
## Acceptance Criteria

- [x] on `items-page` on each `item-card` there is a button called `verkauft...` 
- [x] button opens a popUp with `input` to enter a number
- [x] on popUp there are two buttons: `abbrechen` + `bestätigen`
- [x] `abbrechen` closes the popUp with data unchanged
- [x] `bestätigen` will add the entered number to items data 
- [x] entered number gets displayed on `item-card`
- [x] also `Gewinn` gets calculated depending on actual sellingPrice and gets displayed on `item-card`

## Tasks
                  
- [x] create branch `feature/us19/item-add-soldForPrice` and switch into it
- [x] use or create popUp-component with buttons
- [x] create `button` on `itemCard` to open up the popUp
- [x] add function to edit soldForPrice value for this specific item
- [x] render `real VK:` + calculated `Gewinn` on `item-card` (Gewinn now is real, not calculated with targetPrice anymore)​
