### ISSUE TITLE
US4 // parts - categoryFilter

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#4]
## Value Proposition 

**As a** user  
**I want to** see buttons with categories 
**so that** i can filter all parts by its category
​
    
## Description

![US4](https://github.com/matschi3/capstone/assets/114819127/0359eabc-f555-4f6e-9d98-040f8d1bcebb)

 

## Acceptance Criteria

- [x] user can see a button for each category
- [x] the buttons are placed on top of the page, right between heading and the listed parts
- [x] the buttons are scrollable horizontally
- [x] the buttons can move out of the viewable-area on left and right
      ​

## Tasks
                  
- [x] create branch
- [x] display a button for each category on dummy categoryData
- [x] filter + display parts depending on the clicked category's button
- [x] add categoryFilter style 
      ​
