### ISSUE TITLE
US20 // items - sort and filter

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#42]
## Value Proposition           
   
**As a** `user` 
**I want to** have some filters
**so that** i can easy find or sort my items
    
## Description 
 

![Image](https://user-images.githubusercontent.com/114819127/253893698-c1c435f2-7e46-48ca-bbbb-5734be38f60c.png)

 

 
    
## Acceptance Criteria

- [ ] on `items` page there are buttons to sort and filter displayed `items`
- [ ] the buttons are placed on top of the page, right between heading and the listed items
- [ ] the buttons are scrollable horizontally
- [ ] the buttons can move out of the viewable-area on left and right when they are too big for screen-width
- [ ] depending on set filters, the correct items gets rendered in the correct order

## Tasks
                  
- [ ] create branch `feature/us20/items-sort-and-filter` and switch into it
- [ ] use filter-component from partsList
- [ ] setup filter/sort-buttons
- [ ] add `const filteredItems` with `.sort()` + `.filter()`
- [ ] handle `filteredItems` into mapped `ItemCard` component in return of `ItemPage`
      ​

**Comment by vaupunkt** [comment]
you could rewrite it into two seperate stories
one for filtering
one for sorting

i think both functions are big enough by themself for seperate stories 😊

**Comment by matschi3** [comment]
// edit split into 20a and 20b
this is 20a now

**Comment by marcbendixen** [comment]
That's a good point. In this case creating two use stories out of it makes sense.
Your pull requests will also become smaller 👍
