### ISSUE TITLE
US21 // item - image upload

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#43]
## Value Proposition           
   
**As a** `user` 
**I want to** upload my own picture as items image
**so that** i instantly spot the different items
    
## Description
 

![Image](https://user-images.githubusercontent.com/114819127/253903066-0cfb5050-2e88-487a-b9c0-ab998fece061.png)

 

 
  
## Acceptance Criteria

- [ ] on `items-page` on each `item-card` there is a button called `+ Foto` 
- [ ] button opens a popUp with `input` to upload a picture
- [ ] on popUp the is a `Foto hochladen` button, starting the upload
- [ ] on popUp's bottom there are two buttons: `abbrechen` + `bestätigen`
- [ ] `abbrechen` closes the popUp with data unchanged
- [ ] `bestätigen` will add the uploaded `imageUrl` to items data 
- [ ] uploaded image gets displayed on `item-card`

## Tasks
                  
- [ ] create branch `feature/us21/item-image-upload` and switch into it
- [ ] use popUp-component.styled to create imgUpload-component
- [ ] create single imgUpload for popup
- [ ] create `button` on `itemCard` to open up the popUp
- [ ] add function to edit imgUrl for this specific item

      ​
