### ISSUE TITLE
US22 // notification on actions

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#44]
## Value Proposition           
   
**As a** `user` 
**I want to** se a notification on relevant actions
**so that** i get some quick feedback
    
## Description
 

![Image](https://user-images.githubusercontent.com/114819127/253910164-8fe44be0-f653-4043-9e5e-525e40bd7a63.png)

 
  
## Acceptance Criteria

see a notification on performed action for:
- [x] new part creation
- [x] part edited
- [x] part deleted
- [x] new item creation
- [ ] item image set
- [ ] targetPrice set
- [ ] soldForPrice set
- [x] new category creation
- [x] category edited
- [x] category deleted

- [x] notification disappears after some time has passed

## Tasks
                  
- [x] create branch `feature/us22/popup-notification` and switch into it
- [x] create popUp-notification-component
- [x] insert popup-notification-component into all functions to fit Acceptance Criteria

      ​

**Comment by marcbendixen** [comment]
Well done, It's always a good idea to inform the user that something happened/worked.

Just my personal preference: besides removing the notification after some time, I (as a user) like to have the option to manually remove it too. For example by adding a tiny "x"/"close" button in the corner of the popup. It's a bit more to work on, therefore you could just keep this in mind 😉

**Comment by matschi3** [comment]
```
- [ ] item image set

- [ ] targetPrice set

- [ ] soldForPrice set
```
skipped to US 'fix' due to avoid merge conflicts with other USs. These must wait :/
