### ISSUE TITLE
US20b // items - filter items

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#45]
## Value Proposition           
   
**As a** `user` 
**I want to** have some sorting option
**so that** i can easy sort my items
    
## Description 
 

![Image](https://user-images.githubusercontent.com/114819127/253953032-c89627c1-5c74-4803-bd75-871d91bc4cdc.png)

 

 
    
## Acceptance Criteria

- [ ] on `items` page there are buttons to filter displayed `items`
- [ ] the buttons are placed on top of the page, right between heading and the listed items
- [ ] the buttons are scrollable horizontally
- [ ] the buttons can move out of the viewable-area on left and right when they are too big for screen-width
- [ ] depending on set filter, the correct items gets rendered in the correct order

## Tasks
                  
- [ ] create branch `feature/us20a/items-filter-only` and switch into it
- [ ] use filter-component from partsList
- [ ] setup filter-buttons
- [ ] add `const filteredItems` with `.filter()`
- [ ] handle `filteredItems` into mapped `ItemCard` component in return of `ItemPage`
      ​

**Comment by matschi3** [comment]
true :D  i wrote it once to be super exact and copy pasted it all over
