### ISSUE TITLE
US5

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#5]
## Value Proposition 

**As a** user  
**I want to** see buttons with different status 
**so that** i can filter all parts by different status set
​
    
## Description

![Image](https://user-images.githubusercontent.com/114819127/248008097-b0490b12-6633-4573-ab12-95baee02c35c.png)

 

## Acceptance Criteria

- [ ] user can see a row of button for different status of parts
- [ ] the buttons are placed on top of the page, right between heading and the categoryFilter
- [ ] the buttons are scrollable horizontally
- [ ] the buttons can move out of the viewable-area on left and right when scrolled
      ​

## Tasks
                  
- [ ] create branch
- [ ] display a button for meaningful status on dummy partsData
- [ ] filter + display parts depending on the clicked statusFilter button
- [ ] add statusFilter style (use component for both) 
      ​

**Comment by julialoeschel** [comment]
Hey, 
hier hat sich die Bedutung für mich etwas in Frage gestellt. 
Der user will nicht die Buttons sehen. 
Der User will eine gefilterte Ansicht, und dafür brauch er die Filterbuttons. 

`As a user
I want to view parts with a certain label
so that I am able to get the rigth information quick. 
​`
oder so. 
Der need ist die gefilterte Liste, nicht die Buttons :) 


bei den Acceptance Criteria fehlt mir noch, das die Buttons auch wirklich etwas filtern. und was wird angezeigt, wenn es keine Ergebnisse gibt?

**Comment by matschi3** [comment]
hey julia,
na klar, nur die buttons zu sehen hat keine Bedeutung für den user. hab oben den text angepasst und in der Acceptance Criteria folgende Punkte hinzugefügt:
- [ ] for different statusFilter button pressed, the displayed parts are filtered by its status
- [ ] if there are no parts available with chosen filter, a text is displayed. ('no parts')

meinst du der fallback text ('no parts') sollte auch noch mit auf die Skizze?

**Comment by julialoeschel** [comment]
Nein, so passt das für mich. 
super!
