### ISSUE TITLE
US25 // cloudinary - delete asset of deleted part

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#54]
## Value Proposition           
   
**As a** `admin` 
**I want to** have unused assets deleted from image database
**so that** it will not get filled up with unused images
    
## Description
 
`N/A`
  
## Acceptance Criteria

- [ ] on part delete at detailed `partCard` an uploaded image gets deleted
- [ ] if the part still uses `defaultImage`, skip image-delete -> only delete part

## Tasks
                  
- [ ] create branch `feature/us25/cloudinary-delete-asset-on-part-delete`
- [ ] use cloudinary API to delete used asset (delete request)
- [ ] eventually request detailed assets-data before, when imgUrl is not enough data for delete-request 
- [ ] do not send delete-request, if parts Image url is `defaultImage`

      ​
