### ISSUE TITLE
US6

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#6]
## Value Proposition        
  
**As a** user  
**I want to** have a form for parts 
**so that** i can add new parts by myself
​
    
## Description

  

![Image](https://user-images.githubusercontent.com/114819127/248173068-c2c100a3-b0b4-4968-9dbf-4e7fdfceba96.png)

 

## Acceptance Criteria

- [ ] user can see a button directing to a new Page with a form on it
- [ ] on the newPart page you can enter name, price and purchasingPrice
- [ ] you can also choose the newParts category by dropdown
- [ ] on the bottom of the form there is a submitButton, submitting and sending user back to parts-page
- [ ] on the top left of the newPart page there is a backButton sending user back to parts-page      ​

## Tasks
                  
- [ ] create branch
- [ ] create new page for createNewParts
- [ ] create a form 
- [ ] create an input field for name, price and the purchasingPlace (+save currency)
- [ ] create a dropdown to choose newParts category from existing categories
- [ ] create a submitButton and handle the submit to save entered data
- [ ] routing user back to parts-page onSubmit
- [ ] create an additional 'back' button routing user back to parts-page
      ​

**Comment by Dariastep** [comment]
Looks good, go for it! :)
