### ISSUE TITLE
US7

### ISSUE THREAD

**Issue by matschi3** [matschi3/capstone#7]
## Value Proposition        
  
**As a** user  
**I want to** have more information on parts
**so that** i can keep track on all details of a single part 
​
    
## Description

  

![Image](https://user-images.githubusercontent.com/114819127/248202480-1c28162c-a2f0-4ace-965a-656038b552de.png)

 

## Acceptance Criteria

- [ ] a click on partsIMG opens a details page on this specific part
- [ ] on the details page you can see all information on this specific part
- [ ] on the top left of the newPart page there is a backButton sending user back to parts-page

## Tasks
                  
- [ ] create branch
- [ ] create partsDetail component
- [ ] setup dynamic routing for parts details pages (onClick on partsIMG)
- [ ] display all relevant partsData from dummy partsData
- [ ] create an additional 'back' button routing user back to parts-page
- [ ] add style to partDetail
      ​

**Comment by julialoeschel** [comment]
lgtm (looks good to me) 

good story 
🚀
